Repository openshift/cluster-api, pull requests merged in 2019-04, with the labels that each got.

#24 Upstream: <880>: openshift: Record machine sync error event
  pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/XS

#28 UPSTREAM: <carry>: openshift: drop machinedeployment
  pkg/controller/BUILD.bazel
  pkg/controller/add_machinedeployment.go
Labels: approved, lgtm, size/S

#29 UPSTREAM: <carry>: openshift: drop machinedeployment
  pkg/controller/BUILD.bazel
  pkg/controller/add_machinedeployment.go
Labels: approved, lgtm, size/S

#30 Upstream: <905>: openshift: Clarify log message for machine-controlle…
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/XS

#31 UPSTREAM: <905>: openshift: Clarify log message for machine-controlle…
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/XS

#26 UPSTREAM: <carry>: openshift: validate machines with openshift specific constraints
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
Labels: approved, lgtm, size/M

#32 UPSTREAM: <871>: openshift: Fix argument order in error message for missing label in Machine object
  pkg/controller/machine/controller.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/XS

#33 UPSTREAM: <carry>: openshift: Ensure drain fail is requeued w/ delay
  pkg/controller/machine/controller.go
  pkg/controller/machine/openshift_controller_test.go
Labels: approved, lgtm, size/M

#35 UPSTREAM: <carry>: openshift: Remove cluster from machine.openshift.io
  pkg/apis/machine/v1beta1/BUILD.bazel
  pkg/apis/machine/v1beta1/cluster_types.go
  pkg/apis/machine/v1beta1/cluster_types_test.go
  pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/BUILD.bazel
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/cluster.go
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/BUILD.bazel
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_cluster.go
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_machine_client.go
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/machine/v1beta1/machine_client.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/machine/v1beta1/BUILD.bazel
  pkg/client/informers_generated/externalversions/machine/v1beta1/cluster.go
  pkg/client/informers_generated/externalversions/machine/v1beta1/interface.go
  pkg/client/listers_generated/machine/v1beta1/BUILD.bazel
  pkg/client/listers_generated/machine/v1beta1/cluster.go
  pkg/client/listers_generated/machine/v1beta1/expansion_generated.go
  pkg/controller/machine/BUILD.bazel
  pkg/controller/machine/actuator.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/controller_test.go
  pkg/controller/machine/testactuator.go
  pkg/controller/machinedeployment/BUILD.bazel
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/BUILD.bazel
  pkg/controller/machineset/controller.go
  pkg/provider/example/actuators/machine/BUILD.bazel
  pkg/provider/example/actuators/machine/machineactuator.go
Labels: approved, lgtm, size/XL
