Repository openshift/cluster-api, pull requests merged in 2019-05, with the labels that each got.

#38 UPSTREAM: <carry>: openshift: Update README to reflect downstream dev
  README.md
Labels: size/M

#39 UPSTREAM: <carry>: openshift: Update README to reflect downstream dev
  README.md
Labels: size/M

#40 Namespace and resync
  cmd/manager/main.go
Labels: lgtm, size/S

#43 UPSTREAM: <carry>: openshift: Ensure delete continues w/o node
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/XS
