Repository openshift/cluster-api, pull requests merged in 2019-08, with the labels that each got.

#58 UPSTREAM: 953: openshift: Allow to use foregroundDeletion for MachineDeployments and MachineSets
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/S

#55 UPSTREAM: <carry>: openshift: Read machine additional printer columns from annotations/labels
  config/crds/machine_v1beta1_machine.yaml
  config/crds/machine_v1beta1_machineset.yaml
  pkg/apis/machine/v1beta1/machine_types.go
  pkg/apis/machine/v1beta1/machineset_types.go
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/M

#63 remove paufantom from repository owners
  OWNERS
Labels: approved, lgtm, size/XS

#44 UPSTREAM: <carry>: openshift: Ensure delete continues w/o node
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/XS

#67 Allow deletion of invalid machines without addresses
  pkg/controller/machine/controller.go
Labels: approved, lgtm, size/S
