Repository openshift/cluster-api, pull requests merged in 2024-02, with the labels that each got.

#194 OCPBUGS-26111: add snyk file
  .snyk
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#195 OCPBUGS-29476: openshift: generate separate manifest for core CAPI CRDs
  openshift/manifests/0000_30_cluster-api_04_cm.core-cluster-api.yaml
  openshift/manifests/0000_30_cluster-api_04_crd.core-cluster-api.yaml
  openshift/tools/go.mod
  openshift/tools/go.sum
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/providers.go
  openshift/tools/vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#196 OCPBUGS-29519: openshift: add CustomNoUpgrade annotation value to feature-set
  openshift/manifests/0000_30_cluster-api_04_cm.core-cluster-api.yaml
  openshift/manifests/0000_30_cluster-api_04_crd.core-cluster-api.yaml
  openshift/tools/go.mod
  openshift/tools/go.sum
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/providers.go
  openshift/tools/vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#197 OCPCLOUD-2517: openshift: promote core CAPI IPAM CRDs to GA
  openshift/manifests/0000_30_cluster-api_04_crd.core-cluster-api.yaml
  openshift/tools/go.mod
  openshift/tools/go.sum
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
  openshift/tools/vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#198 [release-4.15] OCPBUGS-29515: openshift: generate separate manifest for core CAPI CRDs
  openshift/manifests/0000_30_cluster-api_04_cm.core-cluster-api.yaml
  openshift/manifests/0000_30_cluster-api_04_crd.core-cluster-api.yaml
  openshift/tools/go.mod
  openshift/tools/go.sum
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
  openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/providers.go
  openshift/tools/vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
